### ISSUE TITLE
Broken connection to Neurodesktop

### ISSUE THREAD

**Issue by korbinian90** [NeuroDesk/neurodesk-app#32] opened 2023-12-07 04:49 UTC
OS: Windows
Neurodesktop App Version: 1.3.0

The Neurodesk App and The JupyterLab interface worked as usual, but opening the Neurodesktop failed.

Expected Behaviour:
Clicking the Neurodesktop button starts the Apache Guacamole window, where either RDP or VNC desktop connection can be selected

Error:
Instead of Starting the Apache Guacamole window to select the connection, a error 400 (I think) window was shown with some java problem (unfortunately no screenshot).
Restarting the app didn't fix the problem.

Solution:
After "Open Developer Tools -> Application -> Clear site data", the connection worked again

**Comment by iishiishii** [comment] 2024-01-19 04:21
Hi Korbinian.

Thanks for logging the bug. 
If it was fixed by clearing site data, I guess it was due to multiple instances spinned up so I tried to reproduce it by doing so.

Does the error look like this?

![Screenshot from 2024-01-19 14-17-04](https://github.com/NeuroDesk/neurodesk-app/assets/59903692/5f7b8bcf-4cef-46f7-bf4d-ae14fc2209bc)

**Comment by korbinian90** [comment] 2024-01-19 08:40
From what I remember, when clicking on the Neurodesktop button in the Launcher, a new window opened. Instead of the Guacamole window it showed a blank white window with an error. Maybe the javascript error was the same, I unfortunately didn't create a screenshot.

**Comment by iishiishii** [comment] 2024-01-25 04:59
I found the cause of what I can replicate as in the screenshot above. 

Every time new window is opened on top of existing window, docker starts another container with the same name name and try to remove the existing one but failed since the container is still running. 

And cache is not cleared every time we start new window. 

Fixed it in this commit 737f7043d7995398485e6ef303c2e9f3c4c46094 and new release. 
I'll close the issue for now but feel free to re-open if you got the error again.

**Closed by iishiishii** 2024-01-25 04:59 UTC
Labels: bug
